version: '3'

services:
    workone-web:
        image: ghcr.io/grsky360/workone-web
        expose:
            - 80
        restart: always
        labels:
            - "traefik.http.routers.workone-web.rule=Host(`workone.ilio.tech`)"
            - "traefik.http.routers.workone-web.entrypoints=https"
            - "traefik.http.routers.workone-web.tls=true"
            - "traefik.http.routers.workone-api.tls.certresolver=ilio"
            - "traefik.http.services.workone-web.loadbalancer.server.port=80"

    workone-api:
        image: ghcr.io/grsky360/workone-api
        expose:
            - 8080
        restart: always
        labels:
            - "traefik.http.routers.workone-api.rule=Host(`workone.ilio.tech`) && PathPrefix(`/api`)"
            - "traefik.http.routers.workone-api.entrypoints=https"
            - "traefik.http.routers.workone-api.tls=true"
            - "traefik.http.routers.workone-api.tls.certresolver=ilio"
            - "traefik.http.services.workone-api.loadbalancer.server.port=8080"

networks:
    default:
        external:
            name: traefik_default
