version: '3'

services:
    rsshub:
        image: grsky360/rsshub:latest
        restart: always
        ports:
            - '9003:1200'
            - '9014:1201'
        environment:
            NODE_ENV: production
            CACHE_TYPE: redis
            REDIS_URL: 'redis://redis:6379/'
            PUPPETEER_WS_ENDPOINT: 'ws://browserless:3000'
        depends_on:
            - redis
            - browserless
        labels:
            - "traefik.http.routers.rsshub.tls=true"
            - "traefik.http.routers.rsshub.tls.certresolver=ilio"
            - "traefik.http.routers.rsshub.entrypoints=https"
            - "traefik.http.services.rsshub.loadbalancer.server.port=1200"
            - "traefik.http.routers.rsshub.rule=Host(`hub.rss.ilio.tech`)"
            - "traefik.http.routers.rsshub.service=rsshub"
            - "traefik.http.routers.rsshub-doc.tls=true"
            - "traefik.http.routers.rsshub-doc.tls.certresolver=ilio"
            - "traefik.http.routers.rsshub-doc.entrypoints=https"
            - "traefik.http.services.rsshub-doc.loadbalancer.server.port=1201"
            - "traefik.http.routers.rsshub-doc.rule=Host(`doc.rss.ilio.tech`)"
            - "traefik.http.routers.rsshub-doc.service=rsshub-doc"

    browserless:
        image: browserless/chrome
        restart: always

    redis:
        image: redis:alpine
        restart: always

networks:
    default:
        external:
            name: traefik_default
