version: '3'

services:
    rsshub:
        image: diygod/rsshub:latest
        restart: always
        ports:
            - '9003:1200'
        environment:
            NODE_ENV: production
            CACHE_TYPE: redis
            REDIS_URL: 'redis://redis:6379/'
            PUPPETEER_WS_ENDPOINT: 'ws://browserless:3000'
        depends_on:
            - redis
            - browserless
        labels:
            - "traefik.http.routers.rsshub.rule=Host(`hub.rss.ilio.tech`)"
            - "traefik.http.routers.rsshub.entrypoints=https"
            - "traefik.http.routers.rsshub.tls=true"
            - "traefik.http.routers.rsshub.tls.certresolver=ilio"
            - "traefik.http.services.rsshub.loadbalancer.server.port=1200"

    rsshub-doc:
        image: grsky360/rsshub-doc:latest
        environment: 
            DEPLOYMENT_PATH: /dist
        volumes: 
            - /yang/data/rsshub-doc:/dist

    browserless:
        image: browserless/chrome:1.43-chrome-stable
        restart: always

    redis:
        image: redis:alpine
        restart: always

networks:
    default:
        external:
            name: traefik_default
