version: '3'
services:
  miniflux:
    image: miniflux/miniflux:latest
    expose:
      - 8080
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://miniflux:miniflux@db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    restart: always
    labels:
      - "traefik.http.routers.miniflux.tls=true"
      - "traefik.http.routers.miniflux.tls.certresolver=ilio"
      - "traefik.http.routers.miniflux.entrypoints=https"
      - "traefik.http.services.miniflux.loadbalancer.server.port=8080"
      - "traefik.http.routers.miniflux.rule=Host(`rss.ilio.tech`)"

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=miniflux
    volumes:
      - /yang/data/miniflux:/var/lib/postgresql/data
    restart: always

networks:
  default:
    external:
      name: traefik_default
