version: '3'
services:
  miniflux:
    image: miniflux/miniflux:latest
    ports:
      - "9011:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://miniflux:miniflux@db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=miniflux
    volumes:
      - /data0/docker-volumes/miniflux:/var/lib/postgresql/data
