version: '3'

services: 
    gitea-server:
        image: gitea/gitea:1
        ports: 
            - "9009:3000"
            - "9010:22"
        environment: 
            USER_UID: 1000
            USER_GID: 1000
        volumes: 
            - /data0/docker-volumes/gitea:/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        restart: always

