version: '3'
services:
    teamcity-server:
        image: jetbrains/teamcity-server
        ports:
          - "8111:8111"
        volumes:
          - teamcity-server-data:/data/teamcity_server/datadir

    teamcity-agent:
        image: jetbrains/teamcity-agent
        ports:
          - "9090:9090"
        environment:
          SERVER_URL: teamcity-server:8111
        depends_on:
          - teamcity-server
        volumes:
          - teamcity-agent-data:/data/teamcity_agent/conf
          - teamcity-agent-work:/opt/buildagent/work
          - /var/run/docker.sock:/var/run/docker.sock

volumes:
  teamcity-server-data:
  teamcity-agent-data:
  teamcity-agent-work:
