version: '3'

services:
    traefik:
        image: traefik:v2.4
        expose:
            - 8080
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /yang/data/traefik/traefik.yml:/etc/traefik/traefik.yml
            - /yang/data/traefik/conf:/etc/traefik/conf
            - /yang/data/traefik:/etc/traefik
        restart: always
        labels: 
            - "traefik.http.routers.traefik.rule=Host(`router.docker.localhost`)"
            - "traefik.http.routers.traefik.entrypoints=https"
            - "traefik.http.routers.traefik.tls=true"
            # - "traefik.http.routers.traefik.tls.certresolver=le"
            - "traefik.http.services.traefik.loadbalancer.server.port=8080"
