version: '3'

services:
    traefik:
        image: traefik:v2.4
        command: --api.insecure=true --providers.docker
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        deploy:
            placement:
                constraints:
                    - node.role == manager
  
    # nginx:
        # image: nginx:alpine
        

        # //web:
        #     image: nginx
        #     volumes:
        #      - ./templates:/etc/nginx/templates
        #     ports:
        #      - "8080:80"
        #     environment:
        #      - NGINX_HOST=foobar.com
        #      - NGINX_PORT=80