version: '3'

services:
  traefik:
    image: traefik:v2.4
    command: --api.insecure=true --providers.docker
    ports:
      - "8000:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager