version: '3'

services: 
    calibre-web:
        image: technosoft2000/calibre-web
        ports: 
            - 9007:8083
        environment: 
            APP_REPO: https://hub.fastgit.org/janeczku/calibre-web.git
            USE_CONFIG_DIR: 'true'
            SET_CONTAINER_TIMEZONE: 'true'
            CONTAINER_TIMEZONE: Asia/Shanghai
            PGID: 0
            PUID: 0
        volumes: 
            - /data0/docker-volumes/calibre-web/books:/books
            - /data0/docker-volumes/calibre-web/app:/calibre-web/app
            - /data0/docker-volumes/calibre-web/kindlegen:/calibre-web/kindlegen
            - /data0/docker-volumes/calibre-web/config:/calibre-web/config
