version: '3'

services: 
    drone-server:
        image: drone/drone:1
        ports: 
            - 9008:80
        environment: 
            DRONE_GITHUB_CLIENT_ID: ${DRONE_GITHUB_CLIENT_ID}
            DRONE_GITHUB_CLIENT_SECRET: ${DRONE_GITHUB_CLIENT_SECRET}
            DRONE_RPC_SECRET: ${DRONE_RPC_SECRET}
            DRONE_SERVER_HOST: ${DRONE_SERVER_HOST}
            DRONE_SERVER_PROTO: ${DRONE_SERVER_PROTO}
            DRONE_USER_FILTER: ${DRONE_USER_FILTER}
            DRONE_USER_CREATE: ${DRONE_USER_CREATE}
        volumes: 
            - /data0/docker-volumes/drone:/data
        restart: always
