version: '3'

services: 
    drone-server:
        image: drone/drone:1
        ports: 
            - 9008:80
        environment: 
            DRONE_GITEA_SERVER: ${DRONE_GITEA_SERVER}
            DRONE_GITEA_CLIENT_ID: ${DRONE_GITEA_CLIENT_ID}
            DRONE_GITEA_CLIENT_SECRET: ${DRONE_GITEA_CLIENT_SECRET}
            DRONE_RPC_SECRET: ${DRONE_RPC_SECRET}
            DRONE_SERVER_HOST: ${DRONE_SERVER_HOST}
            DRONE_SERVER_PROTO: ${DRONE_SERVER_PROTO}
        volumes: 
            - /data0/docker-volumes/drone:/data
        restart: always
