version: '3'

services: 
    drone-server:
        image: drone/drone:1
        expose: 
            - 80
        environment: 
            DRONE_GITHUB_CLIENT_ID: ${DRONE_GITHUB_CLIENT_ID}
            DRONE_GITHUB_CLIENT_SECRET: ${DRONE_GITHUB_CLIENT_SECRET}
            DRONE_RPC_SECRET: ${DRONE_RPC_SECRET:-rpc_secret}
            DRONE_SERVER_HOST: ${DRONE_SERVER_HOST}
            DRONE_SERVER_PROTO: ${DRONE_SERVER_PROTO}
            DRONE_USER_FILTER: ${DRONE_USER_FILTER}
            DRONE_USER_CREATE: ${DRONE_USER_CREATE}
        volumes: 
            - /yang/data/drone:/data
        restart: always
        labels:
            - "traefik.http.routers.drone.tls=true"
            - "traefik.http.routers.drone.tls.certresolver=ilio"
            - "traefik.http.routers.ndrone.entrypoints=https"
            - "traefik.http.services.drone.loadbalancer.server.port=80"
            - "traefik.http.routers.drone.rule=Host(`ci.ilio.tech`)"

    drone-runner-docker:
        image: drone/drone-runner-docker:1
        ports:
            - 9013:3000
        environment: 
            DRONE_RPC_PROTO: https
            DRONE_RPC_HOST: ci.ilio.tech
            DRONE_RPC_SECRET: ${DRONE_RPC_SECRET:-rpc_secret}
            DRONE_RUNNER_CAPACITY: 3
            DRONE_RUNNER_NAME: drone-runner-docker
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
        restart: always

networks:
    default:
        external:
            name: traefik_default
