version: '3'

services: 
    drone-server:
        image: drone/drone:1
        ports: 
            - 8000:80
        environment: 
            DRONE_GITHUB_CLIENT_ID: ${DRONE_GITHUB_CLIENT_ID}
            DRONE_GITHUB_CLIENT_SECRET: ${DRONE_GITHUB_CLIENT_SECRET}
            DRONE_RPC_SECRET: ${DRONE_RPC_SECRET}
            DRONE_SERVER_HOST: ${DRONE_SERVER_HOST}
            DRONE_SERVER_PROTO: ${DRONE_SERVER_PROTO}
        volumes: 
            - drone_data:/data
        restart: always

volumes: 
    drone_data:
