version: '3'

services:
    nginx:
        image: nginx:alpine
        expose:
            - 80
        volumes:
            - /yang/data/static-pages:/html
            - /yang/data/nginx-conf:/etc/nginx/conf.d
        restart: always
        labels:
            - "traefik.http.routers.nginx.rule=Host(`test-page.docker.localhost`)"
            - "traefik.http.routers.nginx.tls=true"
            # - "traefik.http.routers.nginx.tls.certresolver=le"
            - "traefik.http.routers.nginx.entrypoints=https"
            - "traefik.http.services.nginx.loadbalancer.server.port=80"        

networks:
    default:
        external:
            name: traefik_default
