version: "3"

services:
  freshrss-app:
    image: freshrss/freshrss:alpine
    restart: always
    ports:
      - "9015:80"
    volumes:
      - /yang/docker/volumes/freshrss/data:/var/www/FreshRSS/data
      - /yang/docker/volumes/freshrss/extensions:/var/www/FreshRSS/extensions
    environment:
      CRON_MIN: '15,45'
      TZ: Asia/Shanghai
