version: '2'

services:
  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: filerun
      MYSQL_USER: filerun
      MYSQL_PASSWORD: filerun
      MYSQL_DATABASE: filerun
    volumes:
      - /data0/docker-volumes/filerun/db:/var/lib/mysql

  web:
    image: afian/filerun:libreoffice
    environment:
      FR_DB_HOST: db
      FR_DB_PORT: 3306
      FR_DB_NAME: filerun
      FR_DB_USER: filerun
      FR_DB_PASS: filerun
      APACHE_RUN_USER: www-data
      APACHE_RUN_USER_ID: 33
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_GROUP_ID: 33
    depends_on:
      - db
    links:
      - db:db
    expose:
      - 80
    volumes:
      - /yang/data/filerun/html:/var/www/html
      - /yang/data/filerun/file:/user-files
    restart: always
    labels:
      - "traefik.http.routers.filerun.tls=true"
      - "traefik.http.routers.filerun.tls.certresolver=ilio"
      - "traefik.http.routers.filerun.entrypoints=https"
      - "traefik.http.services.filerun.loadbalancer.server.port=80"
      - "traefik.http.routers.filerun.rule=Host(`share.ilio.tech`)"
  
networks:
  default:
    external:
      name: traefik_default